// config.bin - 08:21:27 03/25/14, generated in 0.11 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define true	1
#define false	0

#define private		0
#define protected		1
#define public		2

#define VSoft		0
#define VArmor		1
#define VAir		2

#define TEast		0
#define TWest		1
#define TGuerrila		2
#define TCivilian		3
#define TSideUnknown		4
#define TEnemy		5
#define TFriendly		6
#define TLogic		7

class CfgPatches
{
	class dayz_weapons
	{
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"dayz_anim"};
	};
};

class CfgMovesBasic {
	class ManActions {
		GestureSwing = " ";
	};
	
	class Actions {
		class NoActions : ManActions {
			GestureSwing[] = {"GestureSwing", "Gesture"};
		};
	};
};

class CfgGesturesMale {
	skeletonName = "OFP2_ManSkeleton";
	
	class ManActions {};
	
	class Actions {
		class NoActions {
			turnSpeed = 0;
			upDegree = 0;
			limitFast = 1;
			useFastMove = 0;
		};
	};
	
	class Default {
		actions = "NoActions";
		file = "";
		looped = true;
		speed = 0.5;
		relSpeedMin = 1;
		relSpeedMax = 1;
		soundEnabled = false;
		soundOverride = "";
		soundEdge[] = {0.5, 1};
		terminal = false;
		equivalentTo = "";
		connectAs = "";
		connectFrom[] = {};
		connectTo[] = {};
		interpolateWith[] = {};
		interpolateTo[] = {};
		interpolateFrom[] = {};
		mask = "empty";
		interpolationSpeed = 6;
		interpolationRestart = false;
		preload = false;
		disableWeapons = true;
		enableOptics = true;
		showWeaponAim = true;
		enableMissile = true;
		enableBinocular = true;
		showItemInHand = false;
		showItemInRightHand = false;
		showHandGun = false;
		canPullTrigger = true;
		walkcycles = 1;
		headBobMode = 0;
		headBobStrength = 0;
		leftHandIKBeg = false;
		leftHandIKEnd = false;
		rightHandIKBeg = false;
		rightHandIKEnd = false;
		leftHandIKCurve[] = {1};
		rightHandIKCurve[] = {1};
		forceAim = 0;
	};
	
	class States {
		class GestureSwing : Default {
			file = "\dayz_weapons\anim\melee_hatchet_swing.rtm";
			looped = false;
			speed = 1.28205;
			mask = "handsWeapon";
			headBobStrength = 0.2;
			headBobMode = 2;
			rightHandIKBeg = false;
			rightHandIKEnd = false;
		};
	};
	
	class BlendAnims {
		handsWeapon[] = {"head", 1, "neck1", 1, "neck", 1, "weapon", 1, "LeftShoulder", 1, "LeftArm", 1, "LeftArmRoll", 1, "LeftForeArm", 1, "LeftForeArmRoll", 1, "LeftHand", 1, "LeftHandRing", 1, "LeftHandPinky1", 1, "LeftHandPinky2", 1, "LeftHandPinky3", 1, "LeftHandRing1", 1, "LeftHandRing2", 1, "LeftHandRing3", 1, "LeftHandMiddle1", 1, "LeftHandMiddle2", 1, "LeftHandMiddle3", 1, "LeftHandIndex1", 1, "LeftHandIndex2", 1, "LeftHandIndex3", 1, "LeftHandThumb1", 1, "LeftHandThumb2", 1, "LeftHandThumb3", 1, "RightShoulder", 1, "RightArm", 1, "RightArmRoll", 1, "RightForeArm", 1, "RightForeArmRoll", 1, "RightHand", 1, "RightHandRing", 1, "RightHandPinky1", 1, "RightHandPinky2", 1, "RightHandPinky3", 1, "RightHandRing1", 1, "RightHandRing2", 1, "RightHandRing3", 1, "RightHandMiddle1", 1, "RightHandMiddle2", 1, "RightHandMiddle3", 1, "RightHandIndex1", 1, "RightHandIndex2", 1, "RightHandIndex3", 1, "RightHandThumb1", 1, "RightHandThumb2", 1, "RightHandThumb3", 1, "Spine", 0.2, "Spine1", 0.3, "Spine2", 1, "Spine3", 1};
	};
};

class CfgCloudlets {
	class Default;	// External class reference
	
	class FlareSmoke : Default {
		interval = 0.1;
		circleRadius = 0;
		circleVelocity[] = {0, 0, 0};
		particleShape = "\Ca\Data\ParticleEffects\Universal\Universal";
		particleFSNtieth = 16;
		particleFSIndex = 7;
		particleFSFrameCount = 48;
		particleFSLoop = 1;
		angleVar = 1;
		animationName = "";
		particleType = "Billboard";
		timerPeriod = 1;
		lifeTime = 2;
		moveVelocity[] = {0, 0.6, 0};
		rotationVelocity = 0;
		weight = 0.05;
		volume = 0.04;
		rubbing = 0.05;
		size[] = {0.2, 0.8, 2.6};
		sizeCoef = 1;
		color[] = {{0.6, 0.6, 0.6, 0}, {0.7, 0.7, 0.7, 0.2}, {0.8, 0.8, 0.8, 0.1}, {1, 1, 1, 0}};
		colorCoef[] = {1, 1, 1, 1};
		animationSpeed[] = {1.5, 0.5};
		animationSpeedCoef = 1;
		randomDirectionPeriod = 0.4;
		randomDirectionIntensity = 0.09;
		onTimerScript = "";
		beforeDestroyScript = "";
		lifeTimeVar = 0.3;
		position[] = {0, 0, 0};
		positionVar[] = {0.1, 0.2, 0.1};
		MoveVelocityVar[] = {0.05, 0.5, 0.05};
		rotationVelocityVar = 0;
		sizeVar = 0.3;
		colorVar[] = {0, 0, 0, 0.1};
		randomDirectionPeriodVar = 0.2;
		randomDirectionIntensityVar = 0.05;
	};
	
	class FlareSparks : Default {
		interval = 0.03;
		circleRadius = 0;
		circleVelocity[] = {0, 0, 0};
		particleShape = "\ca\Data\ParticleEffects\Universal\Universal";
		particleFSNtieth = 16;
		particleFSIndex = 13;
		particleFSFrameCount = 2;
		particleFSLoop = 0;
		angleVar = 1;
		animationName = "";
		particleType = "Billboard";
		timerPeriod = 3;
		lifeTime = 0.5;
		moveVelocity[] = {0, 0.7, 0};
		rotationVelocity = 0;
		weight = 0.05;
		volume = 0.04;
		rubbing = 0.05;
		size[] = {0.7, 0};
		sizeCoef = 1;
		color[] = {{1, 1, 1, 0}, {1, 1, 1, -1}, {1, 1, 1, -1}, {1, 1, 1, -1}, {1, 1, 1, -1}, {1, 1, 1, 0}};
		colorCoef[] = {1, 1, 1, 1};
		animationSpeed[] = {1};
		animationSpeedCoef = 1;
		randomDirectionPeriod = 0;
		randomDirectionIntensity = 0;
		onTimerScript = "";
		beforeDestroyScript = "";
		lifeTimeVar = 0.2;
		position[] = {0, 0, 0};
		positionVar[] = {0.05, 0.2, 0.05};
		moveVelocityVar[] = {0.08, 0.9, 0.08};
		rotationVelocityVar = 0;
		sizeVar = 0.06;
		colorVar[] = {0.1, 0.1, 0.1, 0};
		randomDirectionPeriodVar = 0;
		randomDirectionIntensityVar = 0;
	};
	
	class BottleGlassShards : Default {
		interval = 0.001;
		circleRadius = 0;
		circleVelocity[] = {0, 0, 0};
		particleShape = "\ca\Data\ParticleEffects\Universal\GlassShards";
		particleFSNtieth = 1;
		particleFSIndex = 0;
		particleFSFrameCount = 1;
		particleFSLoop = 0;
		angleVar = 1;
		animationName = "";
		particleType = "SpaceObject";
		timerPeriod = 3;
		lifeTime = 2;
		moveVelocity[] = {0, 1, 0};
		rotationVelocity = 2;
		weight = 10;
		volume = 1;
		rubbing = 0;
		size[] = {0.05};
		sizeCoef = 1;
		color[] = {{1, 1, 1, 1}};
		colorCoef[] = {1, 1, 1, 1};
		animationSpeed[] = {1000};
		animationSpeedCoef = 1;
		randomDirectionPeriod = 0;
		randomDirectionIntensity = 0;
		onTimerScript = "";
		beforeDestroyScript = "";
		lifeTimeVar = 0.5;
		position[] = {0, 0, 0};
		positionVar[] = {0.02, 0.02, 0.02};
		moveVelocityVar[] = {0.2, 1, 0.2};
		rotationVelocityVar = 1;
		sizeVar = 0.04;
		colorVar[] = {0.1, 0.1, 0.1, 0};
		randomDirectionPeriodVar = 0;
		randomDirectionIntensityVar = 0;
	};
	
	class BottleGlassShards2 : Default {
		interval = 0.001;
		circleRadius = 0;
		circleVelocity[] = {0, 0, 0};
		particleShape = "\ca\Data\ParticleEffects\Universal\GlassShards";
		particleFSNtieth = 1;
		particleFSIndex = 0;
		particleFSFrameCount = 1;
		particleFSLoop = 0;
		angleVar = 1;
		animationName = "";
		particleType = "SpaceObject";
		timerPeriod = 3;
		lifeTime = 2;
		moveVelocity[] = {0, 2, 0};
		rotationVelocity = 2;
		weight = 10;
		volume = 1;
		rubbing = 0;
		size[] = {0.05};
		sizeCoef = 1;
		color[] = {{1, 1, 1, 1}};
		colorCoef[] = {1, 1, 1, 1};
		animationSpeed[] = {1000};
		animationSpeedCoef = 1;
		randomDirectionPeriod = 1;
		randomDirectionIntensity = 1;
		onTimerScript = "";
		beforeDestroyScript = "";
		lifeTimeVar = 0.5;
		position[] = {0, 0.4, 0};
		positionVar[] = {0.04, 0.04, 0.04};
		moveVelocityVar[] = {0.2, 3, 0.2};
		rotationVelocityVar = 0;
		sizeVar = 0.04;
		colorVar[] = {0.1, 0.1, 0.1, 0};
		randomDirectionPeriodVar = 1;
		randomDirectionIntensityVar = 1;
	};
	
	class BottleGlassDust : Default {
		interval = 0.005;
		circleRadius = 0;
		circleVelocity[] = {0, 0, 0};
		particleShape = "\ca\Data\ParticleEffects\Universal\Universal";
		particleFSNtieth = 16;
		particleFSIndex = 12;
		particleFSFrameCount = 8;
		particleFSLoop = 0;
		angleVar = 1;
		animationName = "";
		particleType = "Billboard";
		timerPeriod = 3;
		lifeTime = 0.7;
		moveVelocity[] = {0, 0.7, 0};
		rotationVelocity = 2;
		weight = 1.275;
		volume = 1;
		rubbing = 0;
		size[] = {0.05, 0.15};
		sizeCoef = 1;
		color[] = {{0.5, 0.5, 0.5, 0.1}, {0.5, 0.5, 0.5, 0}};
		colorCoef[] = {1, 1, 1, 1};
		animationSpeed[] = {1000};
		animationSpeedCoef = 1;
		randomDirectionPeriod = 0;
		randomDirectionIntensity = 0;
		onTimerScript = "";
		beforeDestroyScript = "";
		lifeTimeVar = 0.1;
		position[] = {0, 0.4, 0};
		positionVar[] = {0.02, 0.02, 0.02};
		moveVelocityVar[] = {0.2, 0.5, 0.2};
		rotationVelocityVar = 0;
		sizeVar = 0.04;
		colorVar[] = {0.1, 0.1, 0.1, 0};
		randomDirectionPeriodVar = 0;
		randomDirectionIntensityVar = 0;
	};
};

class FlareSparks {
	class FlareSmoke {
		simulation = "particles";
		type = "FlareSmoke";
		position[] = {0, 0, 0};
		intensity = 1;
		interval = 1;
		lifeTime = 1;
	};
	
	class FlareSparks {
		simulation = "particles";
		type = "FlareSparks";
		position[] = {0, 0, 0};
		intensity = 1;
		interval = 1;
		lifeTime = 1;
	};
};

class GlassSmash {
	class BottleGlassShards {
		simulation = "particles";
		type = "BottleGlassShards";
		position[] = {0, 0, 0};
		intensity = 1;
		interval = 1;
		lifeTime = 1;
	};
	
	class BottleGlassShards2 {
		simulation = "particles";
		type = "BottleGlassShards2";
		position[] = {0, 0, 0};
		intensity = 1;
		interval = 1;
		lifeTime = 1;
	};
	
	class BottleGlassDust {
		simulation = "particles";
		type = "BottleGlassDust";
		position[] = {0, 0, 0};
		intensity = 1;
		interval = 1;
		lifeTime = 1;
	};
};