//class CfgMagazines

//No Models

#include "Items\Mats\equip_crossbow_kit.hpp"
#include "Items\Mats\equip_aa_battery.hpp"
#include "Items\Mats\equip_cable_tie.hpp"
#include "Items\Mats\equip_connector_i.hpp"
#include "Items\Mats\equip_connector_L.hpp"
#include "Items\Mats\equip_connector_T.hpp"
#include "Items\Mats\equip_d_battery.hpp"
#include "Items\Mats\equip_duct_tape.hpp"
#include "Items\Mats\equip_empty_barrel.hpp"
#include "Items\Mats\equip_garlic_bulb.hpp"
#include "Items\Mats\equip_herb_box.hpp"
#include "Items\Mats\equip_hobo_fishing_kit.hpp"
#include "Items\Mats\equip_hose.hpp"
#include "Items\Mats\equip_hose_clamp.hpp"
#include "Items\Mats\equip_laser.hpp"
//#include "Items\Mats\equip_metal_rod.hpp"  //not sure why called metal rod? changed to tent poles
#include "Items\Mats\equip_metal_sheet.hpp"
#include "Items\Mats\equip_metal_sheet_rusted.hpp"
#include "Items\Mats\equip_nails.hpp"
#include "Items\Mats\equip_needle.hpp"
#include "Items\Mats\equip_note.hpp"
#include "Items\Mats\equip_paint.hpp"
//#include "Items\Mats\equip_part_camo.hpp"
//#include "Items\Mats\equip_part_silencer.hpp"
#include "Items\Mats\equip_pvc_box.hpp"
#include "Items\Mats\equip_rope.hpp"
#include "Items\Mats\equip_slugsinacan.hpp"
#include "Items\Mats\equip_string.hpp"
#include "Items\Mats\equip_tent_poles.hpp"
#include "Items\Mats\equip_tin_powder.hpp"
#include "Items\Mats\equip_wood_pallet.hpp"
#include "Items\Mats\equip_woodensplint.hpp"
#include "Items\Mats\equip_feathers.hpp"

//no images
//#include "Items\Mats\equip_metal_rod.hpp"
//#include "Items\Mats\equip_rubber_tube.hpp"
//#include "Items\Mats\equip_fuse.hpp"
//#include "Items\Mats\equip_pipecap.hpp"

//100% Mats to be added
#include "Items\Mats\equip_scrapelectronics.hpp"
#include "Items\Mats\equip_carbomb.hpp"
#include "Items\Mats\equip_rag.hpp"
#include "Items\Mats\equip_gauze.hpp"
#include "Items\Mats\equip_gauzepackaged.hpp"
#include "Items\Mats\equip_1inch_metal_pipe.hpp"
#include "Items\Mats\equip_2inch_metal_pipe.hpp"
#include "Items\Mats\equip_rail_screws.hpp"
#include "Items\Mats\equip_weapon_rails.hpp"
#include "Items\Mats\equip_comfreyleafs.hpp"
#include "Items\Mats\equip_floppywire.hpp"
#include "Items\Mats\equip_crate.hpp"
#include "Items\Mats\equip_brick.hpp"

//Need adding to loot table
