/* Example function
class fnc_myFunction { file = "\z\addons\dayz_code\functions\fnc_myFunction.sqf"; };
*/

class CfgFunctions
{
	class actions
	{
		class object_dismantle { file = "\z\addons\dayz_code\actions\object_dismantle.sqf"; };
		class player_addToolbelt { file = "\z\addons\dayz_code\actions\player_addToolbelt.sqf"; };
		class player_addtoBack { file = "\z\addons\dayz_code\actions\player_addtoBack.sqf"; };
		class player_reloadMag { file = "\z\addons\dayz_code\actions\player_reloadMags.sqf"; };
		class player_createstash { file = "\z\addons\dayz_code\actions\player_createstash.sqf"; };
		class player_drinkWater { file = "\z\addons\dayz_code\actions\player_drinkWater.sqf"; };
		class player_consume { file = "\z\addons\dayz_code\actions\player_consume.sqf"; };
		class player_emptyContainer { file = "\z\addons\dayz_code\actions\player_emptyContainer.sqf"; };
		class player_useMeds { file = "\z\addons\dayz_code\actions\player_useMeds.sqf"; };
		class player_useAttchment { file = "\z\addons\dayz_code\actions\player_useAttchment.sqf"; };
		class player_attachAttachment { file = "\z\addons\dayz_code\actions\player_attachAttachment.sqf"; };
		class player_removeAttachment { file = "\z\addons\dayz_code\actions\player_removeAttachment.sqf"; };
		class player_fillWater { file = "\z\addons\dayz_code\actions\water_fill.sqf"; };
		class player_makeFire { file = "\z\addons\dayz_code\actions\player_makefire.sqf"; };
		class player_chopWood { file = "\z\addons\dayz_code\actions\player_chopWood.sqf"; };
		class player_mineStone { file = "\z\addons\dayz_code\actions\player_mineStone.sqf"; };
		class player_build { file = "\z\addons\dayz_code\actions\player_build.sqf"; };
		class object_build { file = "\z\addons\dayz_code\actions\object_build.sqf"; };
		class player_wearClothes { file = "\z\addons\dayz_code\actions\player_wearClothes.sqf"; };
		class player_dropWeapon { file = "\z\addons\dayz_code\actions\player_dropWeapon.sqf"; };
		class object_pickup { file = "\z\addons\dayz_code\actions\object_pickup.sqf"; };
		class player_combineMag { file = "\z\addons\dayz_code\actions\player_combineMags.sqf"; };
		class player_createquiver { file = "\z\addons\dayz_code\actions\player_createQuiver.sqf"; };
		class player_fillquiver { file = "\z\addons\dayz_code\actions\player_fillQuiver.sqf"; };
		class player_switchWeapon { file = "\z\addons\dayz_code\actions\player_switchWeapon.sqf"; };
		class player_gather { file = "\z\addons\dayz_code\actions\player_gather.sqf"; };
		class player_fixBottle { file = "\z\addons\dayz_code\actions\player_fixBottle.sqf"; };
		class player_tearClothes { file = "\z\addons\dayz_code\actions\player_tearClothes.sqf"; };
		class player_fixHatchet { file = "\z\addons\dayz_code\actions\player_fixTools.sqf"; };
		class player_sharpen { file = "\z\addons\dayz_code\actions\player_sharpen.sqf"; };
		class player_craftItem { file = "\z\addons\dayz_code\actions\player_craftItem.sqf"; };
		class player_craftItemGUI { file = "\z\addons\dayz_code\actions\player_craftItemGUI.sqf"; };
		class player_checkRecipe { file = "\z\addons\dayz_code\actions\player_checkRecipe.sqf"; };
		class object_upgradeFireplace { file = "\z\addons\dayz_code\actions\object_upgradeFireplace.sqf"; };
	};
	
	class compile
	{
		class spawn_flies { file = "\z\addons\dayz_code\compile\spawn_flies.sqf"; };
		class player_zombieCheck { file = "\z\addons\dayz_code\compile\player_zombieCheck.sqf"; };
		class player_zombieAttack { file = "\z\addons\dayz_code\compile\player_zombieAttack.sqf"; };
		class player_attackdelay { file = "\z\addons\dayz_code\compile\player_attackfsmdelay.sqf"; };
		class fnc_usec_damageActions { file = "\z\addons\dayz_code\compile\fn_damageActions.sqf"; };
		class fnc_inAngleSector { file = "\z\addons\dayz_code\compile\fn_inAngleSector.sqf"; };
		class fnc_usec_selfActions { file = "\z\addons\dayz_code\compile\fn_selfActions.sqf"; };
		class fnc_usec_upgradeActions { file = "\z\addons\dayz_code\compile\fn_upgradeActions.sqf"; };
		class fnc_usec_unconscious { file = "\z\addons\dayz_code\compile\fn_unconscious.sqf"; };
		class player_temp_calculation { file = "\z\addons\dayz_code\compile\fn_temperatur.sqf"; };
		class player_weaponFiredNear { file = "\z\addons\dayz_code\compile\player_weaponFiredNear.sqf"; };
		class player_spawnCheck { file = "\z\addons\dayz_code\compile\player_spawnCheck.sqf"; };
		class building_spawnLoot { file = "\z\addons\dayz_code\compile\building_spawnLoot.sqf"; };
		class building_spawnZombies { file = "\z\addons\dayz_code\compile\building_spawnZombies.sqf"; };
		class player_fired { file = "\z\addons\dayz_code\compile\player_fired.sqf"; };
		class player_packTent { file = "\z\addons\dayz_code\compile\player_packTent.sqf"; };
		class player_updateGui { file = "\z\addons\dayz_code\compile\player_updateGui.sqf"; };
		class player_crossbowBolt { file = "\z\addons\dayz_code\compile\player_crossbowBolt.sqf"; };
		class stream_locationFill { file = "\z\addons\dayz_code\compile\stream_locationFill.sqf"; };
		class stream_locationDel { file = "\z\addons\dayz_code\compile\stream_locationDel.sqf"; };
		class stream_locationCheck { file = "\z\addons\dayz_code\compile\stream_locationCheck.sqf"; };
		class player_music { file = "\z\addons\dayz_code\compile\player_music.sqf"; };
		class player_death { file = "\z\addons\dayz_code\compile\player_death.sqf"; };
		class player_switchModel { file = "\z\addons\dayz_code\compile\player_switchModel.sqf"; };
		class player_checkStealth { file = "\z\addons\dayz_code\compile\player_checkStealth.sqf"; };
		class world_sunRise { file = "\z\addons\dayz_code\compile\fn_sunRise.sqf"; };
		class world_surfaceNoise { file = "\z\addons\dayz_code\compile\fn_surfaceNoise.sqf"; };
		class player_humanityMorph { file = "\z\addons\dayz_code\compile\player_humanityMorph.sqf"; };
		class player_throwObject { file = "\z\addons\dayz_code\compile\player_throwObject.sqf"; };
		class player_alertZombies { file = "\z\addons\dayz_code\compile\player_alertZombies.sqf"; };
		class player_countMagazines { file = "\z\addons\dayz_code\compile\player_countMagazines.sqf"; };
		class player_forceSave { file = "\z\addons\dayz_code\compile\player_forceSave.sqf"; };
		class player_Bubble { file = "\z\addons\dayz_code\compile\player_Bubble.sqf"; };
		class object_roadFlare { file = "\z\addons\dayz_code\compile\object_roadFlare.sqf"; };
		class object_setpitchbank { file = "\z\addons\dayz_code\compile\fn_setpitchbank.sqf"; };
		class object_monitorGear { file = "\z\addons\dayz_code\compile\object_monitorGear.sqf"; };
		class vehicle_getOut { file = "\z\addons\dayz_code\compile\vehicle_getOut.sqf"; };
		class zombie_findTargetAgent { file = "\z\addons\dayz_code\compile\zombie_findTargetAgent.sqf"; };
		class player_zombieSwarmAttack { file = "\z\addons\dayz_code\compile\player_zombieSwarmAttack.sqf"; };
		class zombie_loiter { file = "\z\addons\dayz_code\compile\zombie_loiter.sqf"; };
		class zombie_generate { file = "\z\addons\dayz_code\compile\zombie_generate.sqf"; };
		class player_selectSlot { file = "\z\addons\dayz_code\compile\ui_selectSlot.sqf"; };
		class player_gearSet { file = "\z\addons\dayz_code\compile\player_gearSet.sqf"; };
		class ui_changeDisplay { file = "\z\addons\dayz_code\compile\ui_changeDisplay.sqf"; };
		class ui_gear_sound { file = "\z\addons\dayz_code\compile\ui_gear_sound.sqf"; };
		class infectedcamps { file = "\z\addons\dayz_code\compile\object_infectedcamps.sqf"; };
		class fn_updateCraftUI { file = "\z\addons\dayz_code\compile\fn_updateCraftUI.sqf"; };
		class fn_buildCamera { file = "\z\addons\dayz_code\compile\fn_buildCamera.sqf"; };
		class BIS_fnc_selectRandom { file = "\z\addons\dayz_code\compile\fn_selectRandom.sqf"; };
		class fnc_buildWeightedArray { file = "\z\addons\dayz_code\compile\fn_buildWeightedArray.sqf"; };
		class object_getHit { file = "\z\addons\dayz_code\compile\object_getHit.sqf"; };
		class object_setHit { file = "\z\addons\dayz_code\compile\object_setHit.sqf"; };
		class object_processHit { file = "\z\addons\dayz_code\compile\object_processHit.sqf"; };
		class fnc_usec_damageHandler { file = "\z\addons\dayz_code\compile\fn_damageHandler.sqf"; };
		class fnc_veh_handleDam { file = "\z\addons\dayz_code\compile\veh_handleDam.sqf"; };
		class fnc_veh_handleKilled { file = "\z\addons\dayz_code\compile\veh_handleKilled.sqf"; };
		class fnc_veh_handleRepair { file = "\z\addons\dayz_code\compile\veh_handleRepair.sqf"; };
		class fnc_veh_setFixServer { file = "\z\addons\dayz_code\compile\veh_setFixServer.sqf"; };
		class fnc_inString { file = "\z\addons\dayz_code\compile\fn_inString.sqf"; };
		class fnc_isInsideBuilding { file = "\z\addons\dayz_code\compile\fn_isInsideBuilding.sqf"; };
		class dayz_zombieSpeak { file = "\z\addons\dayz_code\compile\object_speak.sqf"; };
		class vehicle_getHitpoints { file = "\z\addons\dayz_code\compile\vehicle_getHitpoints.sqf"; };
		class local_gutObject { file = "\z\addons\dayz_code\compile\local_gutObject.sqf"; };
		class local_zombieDamage { file = "\z\addons\dayz_code\compile\fn_damageHandlerZ.sqf"; };
		class local_setFuel { file = "\z\addons\dayz_code\compile\local_setFuel.sqf"; };
		class local_eventKill { file = "\z\addons\dayz_code\compile\local_eventKill.sqf"; };
		class player_humanityChange { file = "\z\addons\dayz_code\compile\player_humanityChange.sqf"; };
		class spawn_loot { file = "\z\addons\dayz_code\compile\spawn_loot.sqf"; };
		class player_projectileNear { file = "\z\addons\dayz_code\compile\player_projectileNear.sqf"; };
		class fn_selectRandomLocation { file = "\z\addons\dayz_code\compile\fn_selectRandomLocation.sqf"; };
		class fn_chance { file = "\z\addons\dayz_code\compile\fn_selectRandomChance.sqf"; };
		class fn_niceSpot { file = "\z\addons\dayz_code\compile\fn_niceSpot.sqf"; };
	};
};