#define CT_STATIC				0x0
#define CT_BUTTON				0x1
#define CT_EDIT					0x2
#define CT_SLIDER				0x3
#define CT_COMBO				0x4
#define CT_LISTBOX				0x5
#define CT_TOOLBOX				0x6
#define CT_CHECKBOXES			0x7
#define CT_PROGRESS				0x8
#define CT_HTML					0x9
#define CT_STATIC_SKEW			0xA
#define CT_ACTIVETEXT			0xB
#define CT_TREE					0xC
#define CT_STRUCTURED_TEXT		0xD
#define CT_CONTEXT_MENU			0xE
#define CT_CONTROLS_GROUP		0xF
#define CT_SHORTCUTBUTTON		0x10
#define CT_XKEYDESC				0x28
#define CT_XBUTTON				0x29
#define CT_XLISTBOX				0x2A
#define CT_XSLIDER				0x2B
#define CT_XCOMBO				0x2C
#define CT_ANIMATED_TEXTURE		0x2D
#define CT_OBJECT				0x50
#define CT_OBJECT_ZOOM			0x51
#define CT_OBJECT_CONTAINER		0x52
#define CT_OBJECT_CONT_ANIM		0x53
#define CT_LINEBREAK			0x62
#define CT_ANIMATED_USER		0x63
#define CT_MAP					0x64
#define CT_MAP_MAIN				0x65
#define CT_LISTNBOX				0x66
#define CT_ITEMSLOT				0x67